use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum AbilityType {
    Gender,
    Birthstone,
    Class,
    Union,
    Rank,
    Fame,
    Face,
    Hair,

    Strength,
    Dexterity,
    Intelligence,
    Concentration,
    Charm,
    Sense,

    Health,
    Mana,
    Attack,
    Defence,
    Hit,
    Resistance,
    Avoid,
    Speed,
    AttackSpeed,
    Weight,
    Critical,
    RecoverHealth,
    RecoverMana,

    SaveMana,
    Experience,
    Level,
    BonusPoint,
    PvpFlag,
    TeamNumber,
    HeadSize,
    BodySize,
    Skillpoint,
    MaxHealth,
    MaxMana,
    Money,

    PassiveAttackPowerUnarmed,
    PassiveAttackPowerOneHanded,
    PassiveAttackPowerTwoHanded,
    PassiveAttackPowerBow,
    PassiveAttackPowerGun,
    PassiveAttackPowerStaffWand,
    PassiveAttackPowerAutoBow,
    PassiveAttackPowerKatarPair,

    PassiveAttackSpeedBow,
    PassiveAttackSpeedGun,
    PassiveAttackSpeedPair,

    PassiveMoveSpeed,
    PassiveDefence,
    PassiveMaxHealth,
    PassiveMaxMana,
    PassiveRecoverHealth,
    PassiveRecoverMana,
    PassiveWeight,

    PassiveBuySkill,
    PassiveSellSkill,
    PassiveSaveMana,
    PassiveMaxSummons,
    PassiveDropRate,

    Race,
    DropRate,
    FameG,
    FameB,
    CurrentPlanet,
    Stamina,
    Fuel,
    Immunity,

    UnionPoint1,
    UnionPoint2,
    UnionPoint3,
    UnionPoint4,
    UnionPoint5,
    UnionPoint6,
    UnionPoint7,
    UnionPoint8,
    UnionPoint9,
    UnionPoint10,

    GuildNumber,
    GuildScore,
    GuildPosition,

    BankFree,
    BankAddon,
    StoreSkin,
    VehicleHealth,

    PassiveResistance,
    PassiveHit,
    PassiveCritical,
    PassiveAvoid,
    PassiveShieldDefence,
    PassiveImmunity,
}
